Warning busting pull request
Lun4t1c/DiscSpaceBuddy pull request #9
Opened 2023-11-03 20:28 UTC by VoiciehBy

![N9fcDsc](https://github.com/Lun4t1c/DiscSpaceBuddy/assets/43652981/085f17d9-fb00-4d9f-8a3a-e28f0e55f6f5)

2023-11-05 17:16 UTC, Lun4t1c requested changes

2023-11-05 17:16 UTC, Lun4t1c commented on src/main/java/com/dsb/console/DsbConsoleMain.java
> +            System.err.println("DsbConsoleMain have thrown ExecutionException, xDddd...");
Zamień to po prostu na e.printStackTrace()

2023-11-05 17:16 UTC, Lun4t1c commented on src/main/java/com/dsb/console/DsbConsoleMain.java
> +            System.err.println("DsbConsoleMain have thrown IOException, xDddd...");
To też

2023-11-05 17:16 UTC, Lun4t1c commented on src/main/java/com/dsb/core/DsbScanner.java
> +                System.err.println("Scanning was interrupted, xDddd...");
printStackTrace()

2023-11-05 17:16 UTC, Lun4t1c commented on src/main/java/com/dsb/core/DsbScanner.java
> +            System.err.println("DsbScanner have thrown ExecutionException, xDddd...");
printStackTrace()

2023-11-05 17:16 UTC, Lun4t1c commented on src/main/java/com/dsb/gui/MainController.java
> +            System.out.println("Something not right with mainController, xDdddd...");
Przywróć na razie wszędzie printStackTrace(), błędy zsuppressuj albo wgl będziemy ignorować, potem się jakoś inaczej to ogarnie ale na razie musimy wiedzieć co dokładnie tam leci w razie co

2023-11-07 20:44 UTC, VoiciehBy commented
Git gut?

2023-11-07 20:52 UTC, Lun4t1c approved these changes

2023-11-07 20:52 UTC, merged